### ISSUE TITLE
works once ... 

### ISSUE THREAD

**Issue by Unixware** [mrclksr/DSBMC-Cli#1]
using this on FreeBSD, detected a FAT32 USB  (/dev/da1) then  after  un-mounted it ,it does not
detect it anymore... dmesg displays the darn device "da1 at umass-sim1 bus 1 scbus5 target 0 lun 0"  and /dev/da1 created but still no detection from that program , unless I have to reboot the system each time (LOLZ)

**Comment by mrclksr** [comment]
Hi @Unixware,

this is a know problem. Upgrade DSBMD to version 1.11.4 (unfortunately not yet in quarterly).

**Comment by Unixware** [comment]
cheers !! I m looking fwd to it...
